import { BetItem, TipsterStat, SportBreakdown, BookieBreakdown } from "./types";

// Dados de demonstração. Só são servidos quando NEXT_PUBLIC_USE_MOCK=1 —
// nunca como fallback silencioso de erro. Stakes calibradas para 1u = R$ 100,00.

export const MOCK_BETS: BetItem[] = [
  {
    id: "bet-1",
    data: "27/08/2026",
    esporte: "Futebol",
    tipster: "MarceloTips",
    partida: "Barcelona x Real Madrid",
    tip: "Ambas Marcam — Sim",
    casa: "Bet365",
    odd: 1.72,
    valor: 200.00,
    unidades: 2.00,
    resultado: "GREEN",
    lucro: 144.00,
  },
  {
    id: "bet-2",
    data: "27/08/2026",
    esporte: "NBA",
    tipster: "DiegoNBA",
    partida: "Lakers x Celtics",
    tip: "LeBron James +25.5 Pontos",
    casa: "BetPix365",
    odd: 1.85,
    valor: 150.00,
    unidades: 1.50,
    resultado: "GREEN",
    lucro: 127.50,
  },
  {
    id: "bet-3",
    data: "26/08/2026",
    esporte: "Futebol",
    tipster: "RafaBets",
    partida: "Palmeiras x Flamengo",
    tip: "Over 2.5 Gols",
    casa: "Betano",
    odd: 2.10,
    valor: 100.00,
    unidades: 1.00,
    resultado: "RED",
    lucro: -100.00,
  },
  {
    id: "bet-4",
    data: "26/08/2026",
    esporte: "NBA",
    tipster: "DiegoNBA",
    partida: "Warriors x Nuggets",
    tip: "Stephen Curry +4.5 Cestas de 3",
    casa: "Novibet",
    odd: 2.20,
    valor: 50.00,
    unidades: 0.50,
    resultado: "PENDENTE",
    lucro: 0.00,
  },
  {
    id: "bet-5",
    data: "25/08/2026",
    esporte: "Futebol",
    tipster: "MarceloTips",
    partida: "Inter Milan x Napoli",
    tip: "ML Inter Milan",
    casa: "Bet365",
    odd: 1.95,
    valor: 200.00,
    unidades: 2.00,
    resultado: "GREEN",
    lucro: 190.00,
  },
  {
    id: "bet-6",
    data: "25/08/2026",
    esporte: "Futebol",
    tipster: "RafaBets",
    partida: "Man City x Arsenal",
    tip: "BTTS + Over 2.5",
    casa: "Sportingbet",
    odd: 2.45,
    valor: 100.00,
    unidades: 1.00,
    resultado: "GREEN",
    lucro: 145.00,
  },
  {
    id: "bet-7",
    data: "24/08/2026",
    esporte: "NBA",
    tipster: "LucasPicks",
    partida: "MEM Grizzlies x DEN Nuggets",
    tip: "Jamal Murray -3.5 Cestas de 3 Convertidas",
    casa: "Betano",
    odd: 1.64,
    valor: 75.00,
    unidades: 0.75,
    resultado: "RED",
    lucro: -75.00,
  },
  {
    id: "bet-8",
    data: "24/08/2026",
    esporte: "Futebol",
    tipster: "MarceloTips",
    partida: "Parma x Juventus",
    tip: "ML Juventus",
    casa: "BetPix365",
    odd: 2.06,
    valor: 75.00,
    unidades: 0.75,
    resultado: "GREEN",
    lucro: 79.50,
  },
  {
    id: "bet-9",
    data: "23/08/2026",
    esporte: "NBA",
    tipster: "LucasPicks",
    partida: "Houston Rockets x NY Knicks",
    tip: "Tari Eason -6.5 Rebotes",
    casa: "Novibet",
    odd: 1.64,
    valor: 50.00,
    unidades: 0.50,
    resultado: "RED",
    lucro: -50.00,
  },
  {
    id: "bet-10",
    data: "23/08/2026",
    esporte: "Futebol",
    tipster: "RafaBets",
    partida: "Genoa x Udinese",
    tip: "Ambas Marcam — Sim",
    casa: "Esporte da Sorte",
    odd: 5.20,
    valor: 75.00,
    unidades: 0.75,
    resultado: "PENDENTE",
    lucro: 0.00,
  },
  {
    id: "bet-11",
    data: "24/08/2026",
    esporte: "Tênis",
    tipster: "LucasPicks",
    partida: "Alcaraz x Sinner",
    tip: "Over 3.5 Sets",
    casa: "Betnacional",
    odd: 2.30,
    valor: 100.00,
    unidades: 1.00,
    // Anulada: stake devolvida, fora da conta de acerto e de ROI
    resultado: "VOID",
    lucro: 0.00,
  },
];

export const MOCK_TIPSTERS: TipsterStat[] = [
  {
    nome: "MarceloTips",
    esportes: ["Futebol", "NBA"],
    avatarColor: "from-[#2D8659] to-[#34d399]",
    initial: "M",
    taxaAcerto: 72,
    totalApostas: 148,
    lucroUnidades: 0.64,
    oddMedia: 1.45,
    acertoDeEquilibrio: 69.0,
    roi: 2.05,
  },
  {
    nome: "RafaBets",
    esportes: ["Futebol"],
    avatarColor: "from-[#3b82f6] to-[#60a5fa]",
    initial: "R",
    taxaAcerto: 65,
    totalApostas: 94,
    lucroUnidades: 0.36,
    oddMedia: 1.58,
    acertoDeEquilibrio: 63.3,
    roi: 1.15,
  },
  {
    nome: "DiegoNBA",
    esportes: ["NBA"],
    avatarColor: "from-[#B8860B] to-[#f59e0b]",
    initial: "D",
    taxaAcerto: 58,
    totalApostas: 67,
    lucroUnidades: 0.16,
    oddMedia: 1.78,
    acertoDeEquilibrio: 56.2,
    roi: 0.51,
  },
  {
    nome: "LucasPicks",
    esportes: ["Futebol", "Tênis"],
    avatarColor: "from-[#C23B22] to-[#f87171]",
    initial: "L",
    taxaAcerto: 48,
    totalApostas: 33,
    lucroUnidades: -0.10,
    oddMedia: 2.05,
    acertoDeEquilibrio: 48.8,
    roi: -0.32,
  },
];

export const MOCK_SPORTS: SportBreakdown[] = [
  {
    esporte: "Futebol",
    icone: "soccer",
    apostas: 198,
    taxaAcerto: 66,
    lucro: 27140.00,
    roi: 678.50,
  },
  {
    esporte: "NBA / Basquete",
    icone: "basketball",
    apostas: 124,
    taxaAcerto: 59,
    lucro: 13920.00,
    roi: 348.00,
  },
  {
    esporte: "Tênis",
    icone: "tennis",
    apostas: 20,
    taxaAcerto: 60,
    lucro: 1300.00,
    roi: 32.50,
  },
];

export const MOCK_BOOKIES: BookieBreakdown[] = [
  { casa: "Bet365", apostas: 87, percentual: 90 },
  { casa: "BetPix365", apostas: 64, percentual: 68 },
  { casa: "Betano", apostas: 52, percentual: 55 },
  { casa: "Novibet", apostas: 41, percentual: 43 },
  { casa: "Sportingbet", apostas: 38, percentual: 40 },
];

/**
 * Resumo mensal de demonstração. Serve para exercitar a tela de histórico,
 * que precisa de vários meses — o MOCK_BETS cobre só um.
 * Inclui um mês negativo de propósito: é o caso que a tela existe para mostrar.
 */
export const MOCK_RESUMO_MESES = [
  { aba: "Agosto26", apostas: 11, greens: 5, reds: 3, pendentes: 2, voids: 1, lucro: 461.0, apostado: 950.0, oddMedia: 2.28 },
  { aba: "Julho26", apostas: 128, greens: 61, reds: 64, pendentes: 0, voids: 3, lucro: 1240.5, apostado: 12800.0, oddMedia: 2.05 },
  { aba: "Junho26", apostas: 96, greens: 39, reds: 55, pendentes: 0, voids: 2, lucro: -880.0, apostado: 9600.0, oddMedia: 2.41 },
  { aba: "Maio26", apostas: 143, greens: 72, reds: 68, pendentes: 0, voids: 3, lucro: 2115.75, apostado: 14300.0, oddMedia: 1.98 },
  { aba: "Abril26", apostas: 87, greens: 41, reds: 44, pendentes: 0, voids: 2, lucro: 305.2, apostado: 8700.0, oddMedia: 2.12 },
];
