import { BetItem, TipsterStat, SportBreakdown, BookieBreakdown } from "./types";

export const MOCK_BETS: BetItem[] = [
  {
    id: "bet-1",
    data: "27/08/2026",
    esporte: "Futebol",
    tipster: "MarceloTips",
    partida: "Barcelona x Real Madrid",
    tip: "Ambas Marcam — Sim",
    casa: "Bet365",
    odd: 1.72,
    valor: 4.0,
    unidades: 2.0,
    resultado: "GREEN",
    lucro: 2.88,
  },
  {
    id: "bet-2",
    data: "27/08/2026",
    esporte: "NBA",
    tipster: "DiegoNBA",
    partida: "Lakers x Celtics",
    tip: "LeBron James +25.5 Pontos",
    casa: "BetPix365",
    odd: 1.85,
    valor: 3.0,
    unidades: 1.5,
    resultado: "GREEN",
    lucro: 2.55,
  },
  {
    id: "bet-3",
    data: "26/08/2026",
    esporte: "Futebol",
    tipster: "RafaBets",
    partida: "Palmeiras x Flamengo",
    tip: "Over 2.5 Gols",
    casa: "Betano",
    odd: 2.10,
    valor: 2.0,
    unidades: 1.0,
    resultado: "RED",
    lucro: -2.0,
  },
  {
    id: "bet-4",
    data: "26/08/2026",
    esporte: "NBA",
    tipster: "DiegoNBA",
    partida: "Warriors x Nuggets",
    tip: "Stephen Curry +4.5 Cestas de 3",
    casa: "Novibet",
    odd: 2.20,
    valor: 1.0,
    unidades: 0.5,
    resultado: "PENDENTE",
    lucro: 0,
  },
  {
    id: "bet-5",
    data: "25/08/2026",
    esporte: "Futebol",
    tipster: "MarceloTips",
    partida: "Inter Milan x Napoli",
    tip: "ML Inter Milan",
    casa: "Bet365",
    odd: 1.95,
    valor: 4.0,
    unidades: 2.0,
    resultado: "GREEN",
    lucro: 3.80,
  },
  {
    id: "bet-6",
    data: "25/08/2026",
    esporte: "Futebol",
    tipster: "RafaBets",
    partida: "Man City x Arsenal",
    tip: "BTTS + Over 2.5",
    casa: "Sportingbet",
    odd: 2.45,
    valor: 2.0,
    unidades: 1.0,
    resultado: "GREEN",
    lucro: 2.90,
  },
  {
    id: "bet-7",
    data: "24/08/2026",
    esporte: "NBA",
    tipster: "LucasPicks",
    partida: "MEM Grizzlies x DEN Nuggets",
    tip: "Jamal Murray -3.5 Cestas de 3 Convertidas",
    casa: "Betano",
    odd: 1.64,
    valor: 1.5,
    unidades: 0.75,
    resultado: "RED",
    lucro: -1.5,
  },
  {
    id: "bet-8",
    data: "24/08/2026",
    esporte: "Futebol",
    tipster: "MarceloTips",
    partida: "Parma x Juventus",
    tip: "ML Juventus",
    casa: "BetPix365",
    odd: 2.06,
    valor: 1.5,
    unidades: 0.75,
    resultado: "GREEN",
    lucro: 1.59,
  },
  {
    id: "bet-9",
    data: "23/08/2026",
    esporte: "NBA",
    tipster: "LucasPicks",
    partida: "Houston Rockets x NY Knicks",
    tip: "Tari Eason -6.5 Rebotes",
    casa: "Novibet",
    odd: 1.64,
    valor: 1.0,
    unidades: 0.5,
    resultado: "RED",
    lucro: -1.0,
  },
  {
    id: "bet-10",
    data: "23/08/2026",
    esporte: "Futebol",
    tipster: "RafaBets",
    partida: "Genoa x Udinese",
    tip: "Ambas Marcam — Sim",
    casa: "Esporte da Sorte",
    odd: 5.20,
    valor: 1.5,
    unidades: 0.75,
    resultado: "PENDENTE",
    lucro: 0,
  },
];

export const MOCK_TIPSTERS: TipsterStat[] = [
  {
    nome: "MarceloTips",
    esportes: ["Futebol", "NBA"],
    avatarColor: "from-[#2D8659] to-[#34d399]",
    initial: "M",
    taxaAcerto: 72,
    totalApostas: 148,
    lucroUnidades: 32,
  },
  {
    nome: "RafaBets",
    esportes: ["Futebol"],
    avatarColor: "from-[#3b82f6] to-[#60a5fa]",
    initial: "R",
    taxaAcerto: 65,
    totalApostas: 94,
    lucroUnidades: 18,
  },
  {
    nome: "DiegoNBA",
    esportes: ["NBA"],
    avatarColor: "from-[#B8860B] to-[#f59e0b]",
    initial: "D",
    taxaAcerto: 58,
    totalApostas: 67,
    lucroUnidades: 8,
  },
  {
    nome: "LucasPicks",
    esportes: ["Futebol", "Tênis"],
    avatarColor: "from-[#C23B22] to-[#f87171]",
    initial: "L",
    taxaAcerto: 48,
    totalApostas: 33,
    lucroUnidades: -5,
  },
];

export const MOCK_SPORTS: SportBreakdown[] = [
  {
    esporte: "Futebol",
    icone: "soccer",
    apostas: 198,
    taxaAcerto: 66,
    lucro: 542.8,
  },
  {
    esporte: "NBA / Basquete",
    icone: "basketball",
    apostas: 124,
    taxaAcerto: 59,
    lucro: 278.4,
  },
  {
    esporte: "Tênis",
    icone: "tennis",
    apostas: 20,
    taxaAcerto: 60,
    lucro: 26.0,
  },
];

export const MOCK_BOOKIES: BookieBreakdown[] = [
  { casa: "Bet365", apostas: 87, percentual: 90 },
  { casa: "BetPix365", apostas: 64, percentual: 68 },
  { casa: "Betano", apostas: 52, percentual: 55 },
  { casa: "Novibet", apostas: 41, percentual: 43 },
  { casa: "Sportingbet", apostas: 38, percentual: 40 },
];
