import type { BetItem } from "./types";

// Dados de demonstração. Só são servidos quando NEXT_PUBLIC_USE_MOCK=1 —
// nunca como fallback silencioso de erro. Stakes calibradas para 1u = R$ 100,00.

export const MOCK_BETS: BetItem[] = [
  {
    id: "bet-1",
    data: "27/08/2026",
    esporte: "Futebol",
    tipster: "MarceloTips",
    partida: "Barcelona x Real Madrid",
    tip: "Ambas Marcam — Sim",
    casa: "Bet365",
    odd: 1.72,
    valor: 200.0,
    unidades: 2.0,
    resultado: "GREEN",
    lucro: 144.0,
  },
  {
    id: "bet-2",
    data: "27/08/2026",
    esporte: "NBA",
    tipster: "DiegoNBA",
    partida: "Lakers x Celtics",
    tip: "LeBron James +25.5 Pontos",
    casa: "BetPix365",
    odd: 1.85,
    valor: 150.0,
    unidades: 1.5,
    resultado: "GREEN",
    lucro: 127.5,
  },
  {
    id: "bet-3",
    data: "26/08/2026",
    esporte: "Futebol",
    tipster: "RafaBets",
    partida: "Palmeiras x Flamengo",
    tip: "Over 2.5 Gols",
    casa: "Betano",
    odd: 2.1,
    valor: 100.0,
    unidades: 1.0,
    resultado: "RED",
    lucro: -100.0,
  },
  {
    id: "bet-4",
    data: "26/08/2026",
    esporte: "NBA",
    tipster: "DiegoNBA",
    partida: "Warriors x Nuggets",
    tip: "Stephen Curry +4.5 Cestas de 3",
    casa: "Novibet",
    odd: 2.2,
    valor: 50.0,
    unidades: 0.5,
    resultado: "PENDENTE",
    lucro: 0.0,
  },
  {
    id: "bet-5",
    data: "25/08/2026",
    esporte: "Futebol",
    tipster: "MarceloTips",
    // Nome acentuado de propósito: é o que o teste de busca sem acento usa, e
    // a planilha real grafa o mesmo time das duas formas.
    partida: "Inter de Milão x Napoli",
    tip: "ML Inter de Milão",
    casa: "Bet365",
    odd: 1.95,
    valor: 200.0,
    unidades: 2.0,
    resultado: "GREEN",
    lucro: 190.0,
  },
  {
    id: "bet-6",
    data: "25/08/2026",
    esporte: "Futebol",
    tipster: "RafaBets",
    partida: "Man City x Arsenal",
    tip: "BTTS + Over 2.5",
    casa: "Sportingbet",
    odd: 2.45,
    valor: 100.0,
    unidades: 1.0,
    resultado: "GREEN",
    lucro: 145.0,
  },
  {
    id: "bet-7",
    data: "24/08/2026",
    esporte: "NBA",
    tipster: "LucasPicks",
    partida: "MEM Grizzlies x DEN Nuggets",
    tip: "Jamal Murray -3.5 Cestas de 3 Convertidas",
    casa: "Betano",
    odd: 1.64,
    valor: 75.0,
    unidades: 0.75,
    resultado: "RED",
    lucro: -75.0,
  },
  {
    id: "bet-8",
    data: "24/08/2026",
    esporte: "Futebol",
    tipster: "MarceloTips",
    partida: "Parma x Juventus",
    tip: "ML Juventus",
    casa: "BetPix365",
    odd: 2.06,
    valor: 75.0,
    unidades: 0.75,
    resultado: "GREEN",
    lucro: 79.5,
  },
  {
    id: "bet-9",
    data: "23/08/2026",
    esporte: "NBA",
    tipster: "LucasPicks",
    partida: "Houston Rockets x NY Knicks",
    tip: "Tari Eason -6.5 Rebotes",
    casa: "Novibet",
    odd: 1.64,
    valor: 50.0,
    unidades: 0.5,
    resultado: "RED",
    lucro: -50.0,
  },
  {
    id: "bet-10",
    data: "23/08/2026",
    esporte: "Futebol",
    tipster: "RafaBets",
    partida: "Genoa x Udinese",
    tip: "Ambas Marcam — Sim",
    casa: "Esporte da Sorte",
    odd: 5.2,
    valor: 75.0,
    unidades: 0.75,
    resultado: "PENDENTE",
    lucro: 0.0,
  },
  {
    id: "bet-11",
    data: "24/08/2026",
    esporte: "Tênis",
    tipster: "LucasPicks",
    partida: "Alcaraz x Sinner",
    tip: "Over 3.5 Sets",
    casa: "Betnacional",
    odd: 2.3,
    valor: 100.0,
    unidades: 1.0,
    // Anulada: stake devolvida, fora da conta de acerto e de ROI
    resultado: "VOID",
    lucro: 0.0,
  },
];

/**
 * Resumo mensal de demonstração. Serve para exercitar a tela de histórico,
 * que precisa de vários meses — o MOCK_BETS cobre só um.
 * Inclui um mês negativo de propósito: é o caso que a tela existe para mostrar.
 */
export const MOCK_RESUMO_MESES = [
  {
    aba: "Agosto26",
    apostas: 11,
    greens: 5,
    reds: 3,
    pendentes: 2,
    voids: 1,
    lucro: 461.0,
    apostado: 950.0,
    oddMedia: 2.28,
  },
  {
    aba: "Julho26",
    apostas: 128,
    greens: 61,
    reds: 64,
    pendentes: 0,
    voids: 3,
    lucro: 1240.5,
    apostado: 12800.0,
    oddMedia: 2.05,
  },
  {
    aba: "Junho26",
    apostas: 96,
    greens: 39,
    reds: 55,
    pendentes: 0,
    voids: 2,
    lucro: -880.0,
    apostado: 9600.0,
    oddMedia: 2.41,
  },
  {
    aba: "Maio26",
    apostas: 143,
    greens: 72,
    reds: 68,
    pendentes: 0,
    voids: 3,
    lucro: 2115.75,
    apostado: 14300.0,
    oddMedia: 1.98,
  },
  {
    aba: "Abril26",
    apostas: 87,
    greens: 41,
    reds: 44,
    pendentes: 0,
    voids: 2,
    lucro: 305.2,
    apostado: 8700.0,
    oddMedia: 2.12,
  },
];
